# Generated by Django 5.2.12 on 2026-03-23 16:27

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shop.models.product_image_upload_path),
        ),
    ]
