# Generated by Django 5.2.12 on 2026-04-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0005_product_care_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("placed", "Placed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=50)),
                ("delivery_city", models.CharField(max_length=255)),
                ("delivery_street", models.CharField(max_length=255)),
                ("delivery_house", models.CharField(max_length=50)),
                ("delivery_apartment", models.CharField(blank=True, max_length=50)),
                ("delivery_postal_code", models.CharField(max_length=20)),
                ("delivery_comment", models.TextField(blank=True)),
                ("subtotal_snapshot", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_snapshot", models.PositiveIntegerField()),
                ("line_total_snapshot", models.PositiveIntegerField()),
                ("product_name_snapshot", models.CharField(max_length=255)),
                ("color_name_snapshot", models.CharField(max_length=100)),
                ("size_name_snapshot", models.CharField(max_length=50)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.productvariant",
                    ),
                ),
            ],
        ),
    ]
